interface weatherConditions {
    [key: number]: string;
}

export const weatherConditions: weatherConditions = {
    1: "clear",
    2: "mostly clear",
    4: "partly cloudy",
    6: "mostly cloudy",
    7: "overcast",
    9: "fog",
    11: "drizzle",
    14: "freezing drizzle",
    17: "freezing rain",
    21: "isolated showers",
    24: "scattered showers",
    27: "showers",
    31: "partly cloudy and periods of light rain",
    32: "partly cloudy and periods of moderate rain",
    33: "partly cloudy and periods of heavy rain",
    34: "mostly cloudy and periods of light rain",
    35: "mostly cloudy and periods of moderate rain",
    36: "mostly cloudy and periods of heavy rain",
    37: "light rain",
    38: "moderate rain",
    39: "heavy rain",
    41: "isolated light sleet showers",
    42: "isolated moderate sleet showers",
    43: "isolated heavy sleet showers",
    44: "scattered light sleet showers",
    45: "scattered moderate sleet showers",
    46: "scattered heavy sleet showers",
    47: "light sleet",
    48: "moderate sleet",
    49: "heavy sleet",
    51: "isolated light snow showers",
    52: "isolated moderate snow showers",
    53: "isolated heavy snow showers",
    54: "scattered light snow showers",
    55: "scattered moderate snow showers",
    56: "scattered heavy snow showers",
    57: "light snowfall",
    58: "moderate snowfall",
    59: "heavy snowfall",
    61: "isolated hail showers",
    64: "scattered hail showers",
    67: "hail showers",
    71: "isolated thundershowers",
    74: "scattered thundershowers",
    77: "thundershowers",
};
